spring:
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:C:\\Users\\safie\\Desktop\\neiu-cs-321\\SJCarpentry
    username: admin
    password:
    driver: org.h2.Driver


estimate:
  orders:
    pageSize: 5